services:
  flask-api:
    build:
      context: .
      dockerfile: core/api/Dockerfile
    container_name: api_basic-flask-api
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
    env_file:
      - .env
    volumes:
      - ./app:/app
      - redis_data:/redis-data
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 main:app
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: api_basic-nginx
    ports:
      - "80:80"
    volumes:
      - ./core/nginx/nginx-simple.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-api
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: api_basic-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge